### ISSUE TITLE
Enable to define bulk attribute extraction rules

### ISSUE THREAD

**Issue by sebastiankruk** [dynatrace-oss/dynatrace-aws-s3-log-forwarder#32]
**Is your feature request related to a problem? Please describe.**
Data that we would like to sent to logs may contain a couple of JSON keys from a larger pool (beyond 2000). Though we could list them all in attribute_extraction_jmespath_expression this would be harder to maintain and may seriously affect performance of ingest, when scanning though the attribute_extraction_jmespath_expression mapping. 

**Describe the solution you'd like**
We would like to define a simple rule where all top level JSON keys are mapped to attributes based on given pattern. 
For example: 
`attribute_extraction_regexp_expression:
    "myattr_$1": "(.+)"
`
would map all top level keys to `myattr_*` attributes.
Since there is a limit on number of attributes created, we should also enable a way to exclude some top level keys from mapping, e.g.,
`attribute_extraction_regexp_expression:
    "exclude!": "(skip|these|keys)"
    "myattr_$1": "(.+)"
`

**Comment by sebastiankruk** [comment]
As the solution based on regex key matching consumes too much resources, the new proposed format will be: 
```yaml
attribute_mapping_from_top_level_json:
  include: start_time, end_time
  exclude: exec_time
  prefix: myattr.
  posfix: _mapped
```
